(()=>{
  const root=document.documentElement,rail=document.querySelector('.rail'),menu=document.querySelector('#menu-toggle');
  const announce=(message)=>{document.querySelector('#live-status').textContent=message};
  function closeMenu(returnFocus=false){rail.classList.remove('open');menu.setAttribute('aria-expanded','false');if(returnFocus)menu.focus()}
  menu.addEventListener('click',()=>{const open=rail.classList.toggle('open');menu.setAttribute('aria-expanded',String(open));if(open)rail.querySelector('.nav-link').focus()});
  document.addEventListener('keydown',event=>{if(event.key==='Escape'&&rail.classList.contains('open'))closeMenu(true)});
  document.querySelectorAll('.nav-link,.quick-nav a').forEach(link=>link.addEventListener('click',()=>{closeMenu();const target=document.querySelector(link.hash);if(target){target.setAttribute('tabindex','-1');target.focus({preventScroll:true})}}));
  document.addEventListener('click',e=>{if(rail.classList.contains('open')&&!rail.contains(e.target)&&!menu.contains(e.target))closeMenu()});
  const themeButton=document.querySelector('#theme-toggle');
  function setTheme(theme){root.dataset.theme=theme;themeButton.textContent=theme==='dark'?'Switch to light view':'Switch to dark view';themeButton.setAttribute('aria-pressed',String(theme==='dark'));try{localStorage.setItem('persistent-bible-theme',theme)}catch{}}
  themeButton.addEventListener('click',()=>setTheme(root.dataset.theme==='dark'?'light':'dark'));
  let saved;try{saved=localStorage.getItem('persistent-bible-theme')}catch{}setTheme(saved==='dark'?'dark':'light');
  const links=[...document.querySelectorAll('.nav-link')];
  if('IntersectionObserver' in window){const observer=new IntersectionObserver(entries=>{for(const entry of entries){if(entry.isIntersecting){links.forEach(link=>{if(link.hash==='#'+entry.target.id)link.setAttribute('aria-current','true');else link.removeAttribute('aria-current')})}}},{rootMargin:'-12% 0px -65% 0px',threshold:0});document.querySelectorAll('section[id]').forEach(section=>observer.observe(section))}
  const copyButton=document.querySelector('#copy-tokens');
  copyButton.addEventListener('click',async()=>{const text=document.querySelector('#tokens-src').textContent;try{copyButton.textContent='Copying…';await Promise.race([navigator.clipboard.writeText(text),new Promise((_,reject)=>setTimeout(()=>reject(new Error('Clipboard timeout')),1200))]);copyButton.textContent='Tokens copied';announce('CSS tokens copied to clipboard.')}catch{const range=document.createRange();range.selectNodeContents(document.querySelector('#tokens-src'));const selection=getSelection();selection.removeAllRanges();selection.addRange(range);copyButton.textContent='Tokens selected';announce('Clipboard unavailable. Tokens selected. Use your system copy shortcut.')}setTimeout(()=>copyButton.textContent='Copy CSS tokens',2500)});
  document.querySelectorAll('[data-demo]').forEach(button=>button.addEventListener('click',()=>{const feedback=button.closest('.product-ui,.specimen').querySelector(':scope > .ui-result,:scope > .demo-feedback');feedback.textContent=button.dataset.demo;announce(button.dataset.demo)}));
  document.querySelector('#validate-field').addEventListener('click',()=>{const input=document.querySelector('#run-name'),hint=document.querySelector('#run-hint');const invalid=!input.value.trim();input.setAttribute('aria-invalid',String(invalid));hint.classList.toggle('error',invalid);hint.textContent=invalid?'Enter a run name to continue.':'Example validated. No workflow has been created.';announce(hint.textContent);if(invalid)input.focus()});
  document.querySelectorAll('[data-download]').forEach(link=>link.addEventListener('click',e=>{e.preventDefault();const kind=link.dataset.download;const content=kind==='css'?document.querySelector('#tokens-src').textContent:document.querySelector('#token-json').textContent;const url=URL.createObjectURL(new Blob([content],{type:kind==='css'?'text/css':'application/json'}));const a=document.createElement('a');a.href=url;a.download='persistent-labs.tokens.'+kind;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);announce('Token download started.')}));
})();
